apiVersion: apps/v1
kind: Deployment
metadata:
  name: fieldwork
  labels:
    app: fieldwork
  namespace: oss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fieldwork
  template:
    metadata:
      labels:
        app: fieldwork
    spec:
      containers:
        - name: fieldwork
          image: 676906203200.dkr.ecr.ap-northeast-2.amazonaws.com/oss-fieldwork:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failure